USE MYSQL;
SHOW TABLES;

-- CREACIÓN DEL USUARIO QUE TENDRÁ SOLO PERMISOS DE LECTURA SOBRE TODAS LAS TABLAS

CREATE USER IF NOT EXISTS 'NicolasRodriguez'@'localhost' IDENTIFIED BY 'hola1234';

-- OTORGACIÓN DEL PERMISO DE SOLO LECTURA DE REGISTROS

GRANT SELECT ON SECONDARYSCHOOL_DATABASE.* TO 'NicolasRodriguez'@'localhost';

-- CREACIÓN DEL USUARIO QUE TENDRÁ PERMISOS DE LECTURA, INSERCIÓN Y MODIFICACIÓN DE DATOS

CREATE USER IF NOT EXISTS 'CristianValles'@'localhost' IDENTIFIED BY 'chau5678';

-- OTORGACIÓN DE LOS PERMISOS DE LECTURA, INSERCIÓN Y MODIFICACIÓN

GRANT SELECT, INSERT, UPDATE ON SECONDARYSCHOOL_DATABASE.* TO 'CristianValles'@'localhost';

-- CREACIÓN DE UN USUARIO QUE SOLO TENDRÁ PERMISOS DE LECTURA SOBRE LA TABLA SUBJECTS (NO PODRÁ ACCEDER A LAS OTRAS TABLAS)

CREATE USER IF NOT EXISTS 'VivianaCaceres'@'localhost' IDENTIFIED BY 'asignaturas2024';

-- OTORGACIÓN DEL PERMISO DE SOLO LECTURA A LA TABLA SUBJECTS 

GRANT SELECT ON SECONDARYSCHOOL_DATABASE.SUBJECTS TO 'VivianaCaceres'@'localhost';



