USE SECONDARYSCHOOL_DATABASE;

SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
SET AUTOCOMMIT = 0;

-- PRIMERA TABLA: SUBJECTS

START TRANSACTION;

-- ELIMINO 3 REGISTROS
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 14;
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 15;
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 16;

-- ROLLBACK
-- COMMIT 

-- VUELVO A REINSERTAR LOS REGISTROS (EN CASO DE HABER APLICADO COMMIT) SI ES QUE ESTOS ERAN IMPORTANTES

-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Química');
-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Informática');
-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Salud y Adolescencia');


-- SEGUNDA TABLA: STUDENTS

START TRANSACTION;
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (5, 'Leandro', 'Dimitri', '2011-05-05', 'Pasteur 143', 'leandimitri@gmail.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (3, 'Tamara', 'Iguacel', '2012-06-14', 'Astillas 274', 'tamiiguacel@gmail.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (10, 'Bautista', 'Freire', '2009-01-25', 'Deheza 1436', 'freirebauti@hotmail.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (14, 'Lourdes', 'Baez', '2008-04-17', 'Polonia 471', 'baezlour@hotmail.com');
SAVEPOINT SP1;
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (7, 'Hernan', 'Urtizberea', '2010-05-03', 'Colonia 6568', 'hernanurtiz@gmail.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (17, 'Mora', 'Lopez', '2007-07-07', 'Las Heras 910', 'lopezmora@outlook.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (6, 'Armando', 'Juarez', '2011-10-22', 'Victoria 54', 'armandojuarez@yahoo.com');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, BIRTH_DATE, ADDRESS, EMAIL) 
VALUES (12, 'Viviana', 'Colman', '2009-09-12', 'Martinto 1500', 'vivicolman@gmail.com');
SAVEPOINT SP2;

-- AGREGO SENTENCIA DE ELIMINACIÓN DEL SAVEPOINT SP1;

-- RELEASE SAVEPOINT SP1;

-- COMMIT;
