USE SECONDARYSCHOOL_DATABASE;

SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0;
SET AUTOCOMMIT = 0;

-- PRIMERA TABLA: SUBJECTS

START TRANSACTION;

-- ELIMINO 3 REGISTROS
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 14;
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 15;
DELETE FROM SUBJECTS WHERE ID_SUBJECT = 16;

-- ROLLBACK
-- COMMIT 

-- VUELVO A REINSERTAR LOS REGISTROS (EN CASO DE HABER APLICADO COMMIT) SI ES QUE ESTOS ERAN IMPORTANTES

-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Química');
-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Informática');
-- INSERT INTO SUBJECTS(SUBJECT_NAME) VALUES ('Salud y Adolescencia');


-- SEGUNDA TABLA: STUDENTS

START TRANSACTION;
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE) 
VALUES (5, 'Leandro', 'Dimitri', 'Pasteur 143', 'leandimitri@gmail.com', '2011-05-05');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE) 
VALUES (3, 'Tamara', 'Iguacel', 'Astillas 274', 'tamiiguacel@gmail.com', '2012-06-14');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE) 
VALUES (10, 'Bautista', 'Freire', 'Deheza 1436', 'freirebauti@hotmail.com', '2009-01-25');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE)  
VALUES (14, 'Lourdes', 'Baez', 'Polonia 471', 'baezlour@hotmail.com', '2008-04-17');
SAVEPOINT SP1;
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE) 
VALUES (7, 'Hernan', 'Urtizberea', 'Colonia 6568', 'hernanurtiz@gmail.com', '2010-05-03');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE)  
VALUES (17, 'Mora', 'Lopez', 'Las Heras 910', 'lopezmora@outlook.com', '2007-07-07');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE)  
VALUES (6, 'Armando', 'Juarez', 'Victoria 54', 'armandojuarez@yahoo.com', '2011-10-22');
INSERT INTO STUDENTS(ID_COURSE, FIRST_NAME, LAST_NAME, ADDRESS, EMAIL, BIRTH_DATE)  
VALUES (12, 'Viviana', 'Colman', 'Martinto 1500', 'vivicolman@gmail.com', '2009-09-12');
SAVEPOINT SP2;

-- AGREGO SENTENCIA DE ELIMINACIÓN DEL SAVEPOINT SP1;

-- RELEASE SAVEPOINT SP1;

-- COMMIT;
